import { IJwtToken, IUserDTO } from '@/types/dto';

export const MOCK_SYSADMIN_USER: IUserDTO = {
  id: 1,
  avatar: '',
  certificate: null,
  modalities: [],
  hospitalID: '31313',
  code: 'sysadmin',
  title: null,
  username: 'sysadmin',
  fullname: 'Nguyễn Văn A',
  phone: null,
  email: 'info@itechcorp.com.vn',
  departmentID: 1,
  certificateID: null,
  signature: null,
  level: 5,
  password: 'abc',
  uuid: '1123213123123',
  department: {
    id: 1,
    hospitalID: '31313',
    code: 'CNTT',
    name: 'PHÒNG CÔNG NGHỆ THÔNG TIN',
    description: null,
    parentID: null,
    enabled: true,
    uuid: '123124124124',
    parent: null,
  },
  groups: [
    {
      modules: [],
      id: 5,
      hospitalID: '31313',
      name: 'BS Đọc Ca',
      description: null,
      roles: [],
      modalities: [
        {
          id: 1,
          hospitalID: '31313',
          uuid: 'a7eb1ed7-2f96-470f-849d-df061b082615',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 22,
            hospitalID: '31313',
            uuid: '3718f792-2771-4266-bbb7-338e7387a4f8',
            code: 'CT0000121123',
            name: 'This room CT1123',
            description: '',
          },
          name: 'May test',
          code: '111',
          institutionName: null,
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: null,
          aeTitle: 'Test1',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          insurance: 0,
          procedures: [],
        },
        {
          id: 2,
          hospitalID: '31313',
          uuid: '629591e3-1d12-42b3-8951-749d27e1c8b0',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 22,
            hospitalID: '31313',
            uuid: '3718f792-2771-4266-bbb7-338e7387a4f8',
            code: 'CT0000121123',
            name: 'This room CT1123',
            description: '',
          },
          name: 'May test',
          code: '111',
          institutionName: null,
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: null,
          aeTitle: 'Test12',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 4,
          hospitalID: '31313',
          uuid: '469b6edf-34e8-40fd-bd59-958f507fa69b',
          group: {
            name: 'group name',
            id: 3,
            hospitalID: '31313',
            uuid: 'e680d309-5b49-440f-80c6-2b265f6342fd',
            code: 'CT',
            index: 1,
            description: 'CT',
          },
          room: {
            id: 37,
            hospitalID: '31313',
            uuid: '7a6fe202-8aef-4246-87d1-afa288e28968',
            code: 'CSS50',
            name: 'JS',
            description: '',
          },
          name: 'May2',
          code: 'MaMay2',
          institutionName: 'BVDK QUOC TE HAI PHONG',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'may2Aetitle',
          ipAddress: '192.168.1.31',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 5,
          hospitalID: '31313',
          uuid: '18f79d4a-d78a-4e39-bd0f-aa70fa11fcd4',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 37,
            hospitalID: '31313',
            uuid: '7a6fe202-8aef-4246-87d1-afa288e28968',
            code: 'CSS50',
            name: 'JS',
            description: '',
          },
          name: 'may3',
          code: 'may3',
          institutionName: 'BVDK QUOC TE HAI PHONG',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'may3aetitle',
          ipAddress: '192.168.1.30',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 3,
          hospitalID: '31313',
          uuid: 'afbe7be1-f912-4c7f-b4a6-e3d2cee5e7d0',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 36,
            hospitalID: '31313',
            uuid: '0694de3c-9ef3-4780-b48d-2c4ff7d6d9e2',
            code: 'alo đây rồi',
            name: 'alo',
            description: '',
          },
          name: 'may1',
          code: 'mamay1',
          institutionName: 'Institution name',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'May1AETittle',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
      ],
      reports: [],
    },
    {
      modules: [],
      id: 4,
      hospitalID: '31313',
      name: 'BS Lâm Sàng',
      description: null,
      roles: [],
      modalities: [
        {
          id: 1,
          hospitalID: '31313',
          uuid: 'a7eb1ed7-2f96-470f-849d-df061b082615',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 22,
            hospitalID: '31313',
            uuid: '3718f792-2771-4266-bbb7-338e7387a4f8',
            code: 'CT0000121123',
            name: 'This room CT1123',
            description: '',
          },
          name: 'May test',
          code: '111',
          institutionName: null,
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: null,
          aeTitle: 'Test1',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 2,
          hospitalID: '31313',
          uuid: '629591e3-1d12-42b3-8951-749d27e1c8b0',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 22,
            hospitalID: '31313',
            uuid: '3718f792-2771-4266-bbb7-338e7387a4f8',
            code: 'CT0000121123',
            name: 'This room CT1123',
            description: '',
          },
          name: 'May test',
          code: '111',
          institutionName: null,
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: null,
          aeTitle: 'Test12',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 4,
          hospitalID: '31313',
          uuid: '469b6edf-34e8-40fd-bd59-958f507fa69b',
          group: {
            name: 'group name',
            id: 3,
            hospitalID: '31313',
            uuid: 'e680d309-5b49-440f-80c6-2b265f6342fd',
            code: 'CT',
            index: 1,
            description: 'CT',
          },
          room: {
            id: 37,
            hospitalID: '31313',
            uuid: '7a6fe202-8aef-4246-87d1-afa288e28968',
            code: 'CSS50',
            name: 'JS',
            description: '',
          },
          name: 'May2',
          code: 'MaMay2',
          institutionName: 'BVDK QUOC TE HAI PHONG',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'may2Aetitle',
          ipAddress: '192.168.1.31',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 5,
          hospitalID: '31313',
          uuid: '18f79d4a-d78a-4e39-bd0f-aa70fa11fcd4',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 37,
            hospitalID: '31313',
            uuid: '7a6fe202-8aef-4246-87d1-afa288e28968',
            code: 'CSS50',
            name: 'JS',
            description: '',
          },
          name: 'may3',
          code: 'may3',
          institutionName: 'BVDK QUOC TE HAI PHONG',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'may3aetitle',
          ipAddress: '192.168.1.30',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 3,
          hospitalID: '31313',
          uuid: 'afbe7be1-f912-4c7f-b4a6-e3d2cee5e7d0',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 36,
            hospitalID: '31313',
            uuid: '0694de3c-9ef3-4780-b48d-2c4ff7d6d9e2',
            code: 'alo đây rồi',
            name: 'alo',
            description: '',
          },
          name: 'may1',
          code: 'mamay1',
          institutionName: 'Institution name',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'May1AETittle',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
      ],
      reports: [],
    },
    {
      modules: [],
      id: 7,
      hospitalID: '31313',
      name: 'BS Lãnh Đạo',
      description: null,
      roles: [],
      modalities: [
        {
          id: 1,
          hospitalID: '31313',
          uuid: 'a7eb1ed7-2f96-470f-849d-df061b082615',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 22,
            hospitalID: '31313',
            uuid: '3718f792-2771-4266-bbb7-338e7387a4f8',
            code: 'CT0000121123',
            name: 'This room CT1123',
            description: '',
          },
          name: 'May test',
          code: '111',
          institutionName: null,
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: null,
          aeTitle: 'Test1',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 2,
          hospitalID: '31313',
          uuid: '629591e3-1d12-42b3-8951-749d27e1c8b0',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 22,
            hospitalID: '31313',
            uuid: '3718f792-2771-4266-bbb7-338e7387a4f8',
            code: 'CT0000121123',
            name: 'This room CT1123',
            description: '',
          },
          name: 'May test',
          code: '111',
          institutionName: null,
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: null,
          aeTitle: 'Test12',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 4,
          hospitalID: '31313',
          uuid: '469b6edf-34e8-40fd-bd59-958f507fa69b',
          group: {
            name: 'group name',
            id: 3,
            hospitalID: '31313',
            uuid: 'e680d309-5b49-440f-80c6-2b265f6342fd',
            code: 'CT',
            index: 1,
            description: 'CT',
          },
          room: {
            id: 37,
            hospitalID: '31313',
            uuid: '7a6fe202-8aef-4246-87d1-afa288e28968',
            code: 'CSS50',
            name: 'JS',
            description: '',
          },
          name: 'May2',
          code: 'MaMay2',
          institutionName: 'BVDK QUOC TE HAI PHONG',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'may2Aetitle',
          ipAddress: '192.168.1.31',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 5,
          hospitalID: '31313',
          uuid: '18f79d4a-d78a-4e39-bd0f-aa70fa11fcd4',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 37,
            hospitalID: '31313',
            uuid: '7a6fe202-8aef-4246-87d1-afa288e28968',
            code: 'CSS50',
            name: 'JS',
            description: '',
          },
          name: 'may3',
          code: 'may3',
          institutionName: 'BVDK QUOC TE HAI PHONG',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'may3aetitle',
          ipAddress: '192.168.1.30',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 3,
          hospitalID: '31313',
          uuid: 'afbe7be1-f912-4c7f-b4a6-e3d2cee5e7d0',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 36,
            hospitalID: '31313',
            uuid: '0694de3c-9ef3-4780-b48d-2c4ff7d6d9e2',
            code: 'alo đây rồi',
            name: 'alo',
            description: '',
          },
          name: 'may1',
          code: 'mamay1',
          institutionName: 'Institution name',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'May1AETittle',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
      ],
      reports: [],
    },
    {
      modules: [],
      id: 1,
      hospitalID: '31313',
      name: 'Admin',
      description: null,
      roles: [],
      modalities: [],
      reports: [],
    },
    {
      modules: [],
      id: 6,
      hospitalID: '31313',
      name: 'BS Duyệt Ca',
      description: null,
      roles: [],
      modalities: [
        {
          id: 1,
          hospitalID: '31313',
          uuid: 'a7eb1ed7-2f96-470f-849d-df061b082615',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 22,
            hospitalID: '31313',
            uuid: '3718f792-2771-4266-bbb7-338e7387a4f8',
            code: 'CT0000121123',
            name: 'This room CT1123',
            description: '',
          },
          name: 'May test',
          code: '111',
          institutionName: null,
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: null,
          aeTitle: 'Test1',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 2,
          hospitalID: '31313',
          uuid: '629591e3-1d12-42b3-8951-749d27e1c8b0',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 22,
            hospitalID: '31313',
            uuid: '3718f792-2771-4266-bbb7-338e7387a4f8',
            code: 'CT0000121123',
            name: 'This room CT1123',
            description: '',
          },
          name: 'May test',
          code: '111',
          institutionName: null,
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: null,
          aeTitle: 'Test12',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 4,
          hospitalID: '31313',
          uuid: '469b6edf-34e8-40fd-bd59-958f507fa69b',
          group: {
            name: 'group name',
            id: 3,
            hospitalID: '31313',
            uuid: 'e680d309-5b49-440f-80c6-2b265f6342fd',
            code: 'CT',
            index: 1,
            description: 'CT',
          },
          room: {
            id: 37,
            hospitalID: '31313',
            uuid: '7a6fe202-8aef-4246-87d1-afa288e28968',
            code: 'CSS50',
            name: 'JS',
            description: '',
          },
          name: 'May2',
          code: 'MaMay2',
          institutionName: 'BVDK QUOC TE HAI PHONG',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'may2Aetitle',
          ipAddress: '192.168.1.31',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 5,
          hospitalID: '31313',
          uuid: '18f79d4a-d78a-4e39-bd0f-aa70fa11fcd4',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 37,
            hospitalID: '31313',
            uuid: '7a6fe202-8aef-4246-87d1-afa288e28968',
            code: 'CSS50',
            name: 'JS',
            description: '',
          },
          name: 'may3',
          code: 'may3',
          institutionName: 'BVDK QUOC TE HAI PHONG',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'may3aetitle',
          ipAddress: '192.168.1.30',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
        {
          id: 3,
          hospitalID: '31313',
          uuid: 'afbe7be1-f912-4c7f-b4a6-e3d2cee5e7d0',
          group: {
            name: 'group name',
            id: 1,
            hospitalID: '31313',
            uuid: 'db4144dc-41a6-457f-8a34-d13bed3246e9',
            code: 'ES',
            index: 0,
            description: 'ES',
          },
          room: {
            id: 36,
            hospitalID: '31313',
            uuid: '0694de3c-9ef3-4780-b48d-2c4ff7d6d9e2',
            code: 'alo đây rồi',
            name: 'alo',
            description: '',
          },
          name: 'may1',
          code: 'mamay1',
          institutionName: 'Institution name',
          manufacturerModelName: null,
          modalityType: null,
          config: '',
          voided: false,
          stationName: 'Station name',
          aeTitle: 'May1AETittle',
          ipAddress: '192.168.1.32',
          capability: 0,
          enabled: true,
          procedures: [],
          insurance: 0,
        },
      ],
      reports: [],
    },
    {
      modules: [],
      id: 8,
      hospitalID: '31313',
      name: 'Trưởng khoa CĐHA',
      description: null,
      roles: [],
      modalities: [],
      reports: [],
    },
    {
      modules: [],
      id: 3,
      hospitalID: '31313',
      name: 'Kỹ Thuật Viên',
      description: null,
      roles: [],
      modalities: [],
      reports: [],
    },
    {
      modules: [],
      id: 2,
      hospitalID: '31313',
      name: 'Lễ Tân',
      description: null,
      roles: [],
      modalities: [],
      reports: [],
    },
  ],
  roles: [],
  type: 'ADMIN',
  enabled: true,
};

export const MOCK_TOKEN: IJwtToken = {
  accessToken: 'tokentoken',
  refreshToken: 'refreshtoken',
  type: 'Bearer',
  expiresIn: 43200,
  expiresAt: Date.now() + 43200,
  issuedAt: Date.now(),
};
